### ISSUE TITLE
Adicionar o Logo dos canais

### ISSUE THREAD

**Issue by marcosisocram** [leuthier/IPTV_Plex#1]
Vou adicionar os logos.
Sabe dizer quais os tipos de imagens que é suportado, jpg e png somente?

**Comment by leuthier** [comment]
Olá Marcos, agradeço seu interesse em contribuir com a lista.

O exemplo tem na página do plugin é com .png:`<tvg-logo="icon-default.png">` <br> Mas o caminho local da imagem pode ser trocada por uma url tb- o que eu acho melhor.
 Já testei com .jpeg e tb funciona.

Infelizmente não sei outros formatos, mas posso testar.
Abraço.
